#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShoppingCart.Droid.Resource", IsApplication=true)]

namespace ShoppingCart.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Splat.Resource.String.library_name = global::ShoppingCart.Droid.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ShoppingCart.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ShoppingCart.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ShoppingCart.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int apptheme_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int tab_host_default_height = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apptheme_activated_background_holo_light = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apptheme_btn_check_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apptheme_btn_check_off_disabled_focused_holo_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apptheme_btn_check_off_disabled_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apptheme_btn_check_off_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apptheme_btn_check_off_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apptheme_btn_check_off_pressed_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apptheme_btn_check_on_disabled_focused_holo_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int apptheme_btn_check_on_disabled_holo_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int apptheme_btn_check_on_focused_holo_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int apptheme_btn_check_on_holo_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int apptheme_btn_check_on_pressed_holo_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int apptheme_btn_default_disabled_focused_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int apptheme_btn_default_disabled_holo_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int apptheme_btn_default_focused_holo_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int apptheme_btn_default_holo_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int apptheme_btn_default_normal_holo_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int apptheme_btn_default_pressed_holo_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int apptheme_btn_radio_holo_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int apptheme_btn_radio_off_disabled_focused_holo_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int apptheme_btn_radio_off_disabled_holo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int apptheme_btn_radio_off_focused_holo_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int apptheme_btn_radio_off_holo_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int apptheme_btn_radio_off_pressed_holo_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int apptheme_btn_radio_on_disabled_focused_holo_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int apptheme_btn_radio_on_disabled_holo_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int apptheme_btn_radio_on_focused_holo_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int apptheme_btn_radio_on_holo_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int apptheme_btn_radio_on_pressed_holo_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int apptheme_btn_rating_star_off_focused_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int apptheme_btn_rating_star_off_normal_holo_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int apptheme_btn_rating_star_off_pressed_holo_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int apptheme_btn_rating_star_on_focused_holo_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int apptheme_btn_rating_star_on_normal_holo_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int apptheme_btn_rating_star_on_pressed_holo_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int apptheme_btn_toggle_holo_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int apptheme_btn_toggle_off_disabled_focused_holo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int apptheme_btn_toggle_off_disabled_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int apptheme_btn_toggle_off_focused_holo_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int apptheme_btn_toggle_off_normal_holo_light = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int apptheme_btn_toggle_off_pressed_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int apptheme_btn_toggle_on_disabled_focused_holo_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int apptheme_btn_toggle_on_disabled_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int apptheme_btn_toggle_on_focused_holo_light = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int apptheme_btn_toggle_on_normal_holo_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int apptheme_btn_toggle_on_pressed_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int apptheme_edit_text_holo_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int apptheme_fastscroll_thumb_default_holo = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int apptheme_fastscroll_thumb_holo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int apptheme_fastscroll_thumb_pressed_holo = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int apptheme_ic_navigation_drawer = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int apptheme_item_background_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int apptheme_list_activated_holo = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int apptheme_list_focused_holo = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int apptheme_list_longpressed_holo = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int apptheme_list_pressed_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int apptheme_list_selector_background_transition_holo_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int apptheme_list_selector_disabled_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int apptheme_list_selector_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int apptheme_progress_bg_holo_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int apptheme_progress_horizontal_holo_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int apptheme_progress_indeterminate_horizontal_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int apptheme_progress_primary_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int apptheme_progress_secondary_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int apptheme_progressbar_indeterminate_holo1 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int apptheme_progressbar_indeterminate_holo2 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int apptheme_progressbar_indeterminate_holo3 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int apptheme_progressbar_indeterminate_holo4 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int apptheme_progressbar_indeterminate_holo5 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int apptheme_progressbar_indeterminate_holo6 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int apptheme_progressbar_indeterminate_holo7 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int apptheme_progressbar_indeterminate_holo8 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int apptheme_rate_star_big_half_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int apptheme_rate_star_big_off_holo_light = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int apptheme_rate_star_big_on_holo_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int apptheme_rate_star_small_half_holo_light = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int apptheme_rate_star_small_off_holo_light = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int apptheme_rate_star_small_on_holo_light = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int apptheme_ratingbar_full_empty_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int apptheme_ratingbar_full_filled_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int apptheme_ratingbar_full_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int apptheme_ratingbar_holo_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int apptheme_ratingbar_small_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int apptheme_scrubber_control_disabled_holo = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int apptheme_scrubber_control_focused_holo = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int apptheme_scrubber_control_normal_holo = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int apptheme_scrubber_control_pressed_holo = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int apptheme_scrubber_control_selector_holo_light = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int apptheme_scrubber_primary_holo = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int apptheme_scrubber_progress_horizontal_holo_light = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int apptheme_scrubber_secondary_holo = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int apptheme_scrubber_track_holo_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int apptheme_spinner_background_holo_light = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int apptheme_spinner_default_holo_light = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int apptheme_spinner_disabled_holo_light = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int apptheme_spinner_focused_holo_light = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int apptheme_spinner_pressed_holo_light = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int apptheme_switch_bg_disabled_holo_light = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int apptheme_switch_bg_focused_holo_light = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int apptheme_switch_bg_holo_light = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int apptheme_switch_inner_holo_light = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int apptheme_switch_thumb_activated_holo_light = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int apptheme_switch_thumb_disabled_holo_light = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int apptheme_switch_thumb_holo_light = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int apptheme_switch_thumb_pressed_holo_light = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int apptheme_switch_track_holo_light = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int apptheme_tab_indicator_holo = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int apptheme_tab_selected_focused_holo = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int apptheme_tab_selected_holo = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int apptheme_tab_selected_pressed_holo = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int apptheme_tab_unselected_focused_holo = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int apptheme_tab_unselected_holo = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int apptheme_tab_unselected_pressed_holo = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int apptheme_text_select_handle_left = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int apptheme_text_select_handle_middle = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int apptheme_text_select_handle_right = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int apptheme_textfield_activated_holo_light = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int apptheme_textfield_default_holo_light = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int apptheme_textfield_disabled_focused_holo_light = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int apptheme_textfield_disabled_holo_light = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int apptheme_textfield_focused_holo_light = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int ic_action_logout = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int Icon = 2130837626;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int contentFrame = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int apptheme_tab_indicator_holo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int zxingscanneractivitylayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int zxingscannerfragmentlayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070013
			public const int AppTheme = 2131165203;
			
			// aapt resource value: 0x7f070001
			public const int AutoCompleteTextViewAppTheme = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ButtonAppTheme = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int CheckBoxAppTheme = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int EditTextAppTheme = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int ImageButtonAppTheme = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int ListViewAppTheme = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int ListViewAppTheme_White = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int ProgressBarAppTheme = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int RadioButtonAppTheme = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int RatingBarAppTheme = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int RatingBarBigAppTheme = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int RatingBarSmallAppTheme = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int SeekBarAppTheme = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int SpinnerAppTheme = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int SpinnerDropDownItemAppTheme = 2131165191;
			
			// aapt resource value: 0x7f070012
			public const int SpinnerItemAppTheme = 2131165202;
			
			// aapt resource value: 0x7f070008
			public const int TabAppTheme = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int TabTextAppTheme = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int ToggleAppTheme = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int _AppTheme = 2131165204;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
